x = int(input("X: "))
y = int(input("Y: ")

print(f"SUM: {x+y}")
print(f"Sub {x-y}" )
print("ras")
print("dev2 changes")
print("tu esea ise aris")
print("gayofa")
print("scenario2 dev1")
print("scenario2 dev1 meore")
